# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'activeadmin'
gem 'bootsnap', require: false
gem 'devise'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'sass-rails'

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
end

group :development, :test do
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'timecop'
  gem 'vcr'
  gem 'webmock'
end
